# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Run test with hugo script
hugo test:
  script:
  - hugo
  except:
  - master

# Build and publish hugo pages to prdocution
build and publis pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
