# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Run yamllint for all .yaml files in repository.
yamllint:
  stage: test
  image: registry.gitlab.com/pipeline-components/yamllint:latest
  script:
    - yamllint .

# Run test with hugo script
test:
  script:
    - hugo
  except:
    - master

# Build and publish hugo pages to prdocution
pages:
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master
