extends: default

rules:
  # fix for truthy warning on github action files
  truthy:
    allowed-values: ['true', 'false', 'on']
  line-length: disable
  document-start: disable
  comments-indentation: disable
  indentation:
    spaces: 2
